version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    env_file:
      - src/.env.mongo.docker
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - src/.env.mongo.docker

  app:
    build: .
    tty: true
    restart: on-failure
    env_file:
      - src/.env.docker
    command: sh -c "uvicorn src.app:app --host 0.0.0.0 --port 8011 --reload"
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "8011:8011"
    volumes:
      - .:/app

volumes:
  mongodb:
  mongodb_config:
